
#DEPLOYMENT COMPOSE FILE

version: '3.8'

services:
  web:
    image: ahzan00/phoenixcart:v.03
    command: gunicorn phoenix_mart.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"  # expose internally for nginx
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./staticfiles:/app/staticfiles 
      - ./media:/app/media

  #postgres db for now  
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - phoenix_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web

volumes:
  phoenix_data:
  static:
  media:

