version: '3.8'

services:
  web:
    build: .
    # The command is now a simple string that will be run by the shell
    command: gunicorn phoenix_mart.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env

